/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Device Status */
        get: operations["device_status_api_device_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Pin */
        post: operations["set_pin_api_pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Places */
        get: operations["list_places_api_places_get"];
        put?: never;
        /** Create Place */
        post: operations["create_place_api_places_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Place */
        delete: operations["remove_place_api_places__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_presets_get"];
        put?: never;
        /** Create Preset */
        post: operations["create_preset_api_presets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Preset */
        delete: operations["remove_preset_api_presets__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Route */
        post: operations["build_route_api_route_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/walk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Walk Status */
        get: operations["walk_status_api_walk_get"];
        put?: never;
        /** Start Walk */
        post: operations["start_walk_api_walk_post"];
        /** Stop Walk */
        delete: operations["stop_walk_api_walk_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/walk/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reroute Walk */
        patch: operations["reroute_walk_api_walk_route_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DeviceStatus */
        DeviceStatus: {
            /** Connected */
            connected: boolean;
            /** Detail */
            detail: string;
            /** Reason */
            reason: string;
        };
        /** FixOut */
        FixOut: {
            /** Distance M */
            distance_m: number;
            /** Elapsed S */
            elapsed_s: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Paused */
            paused: boolean;
            /** Speed Mps */
            speed_mps: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PaceOut
         * @description A selectable pace. Carries `speed_mps` so the GUI can show what picking
         *     it actually means without a second request or a hardcoded copy of the
         *     built-in speeds.
         */
        PaceOut: {
            /** Name */
            name: string;
            /** Speed Mps */
            speed_mps: number;
        };
        /**
         * PinRequest
         * @description A single point to hold the device at — the GUI's `ios-loc set`.
         */
        PinRequest: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** PlaceIn */
        PlaceIn: {
            /** Name */
            name: string;
            /** Point */
            point: [
                number,
                number
            ];
        };
        /** PlaceOut */
        PlaceOut: {
            /** Name */
            name: string;
            /** Point */
            point: number[];
        };
        /** PlacesListOut */
        PlacesListOut: {
            /** Places */
            places: components["schemas"]["PlaceOut"][];
        };
        /** PresetIn */
        PresetIn: {
            /**
             * Costing
             * @default pedestrian
             */
            costing: string;
            /**
             * Loop
             * @default false
             */
            loop: boolean;
            /** Name */
            name: string;
            /**
             * Pace
             * @default walk
             */
            pace: string;
            /** Waypoints */
            waypoints: [
                number,
                number
            ][];
        };
        /** PresetOut */
        PresetOut: {
            /** Costing */
            costing: string;
            /** Loop */
            loop: boolean;
            /** Name */
            name: string;
            /** Pace */
            pace: string;
            /** Waypoints */
            waypoints: number[][];
        };
        /** PresetsListOut */
        PresetsListOut: {
            /** Offline */
            offline: boolean;
            /** Paces */
            paces: components["schemas"]["PaceOut"][];
            /** Presets */
            presets: components["schemas"]["PresetOut"][];
        };
        /**
         * RerouteRequest
         * @description Newly-appended waypoints only -- the running walk's current live
         *     position is prepended server-side by `WalkService.reroute`.
         */
        RerouteRequest: {
            /** Waypoints */
            waypoints: [
                number,
                number
            ][];
        };
        /** RouteRequest */
        RouteRequest: {
            /**
             * Costing
             * @default pedestrian
             */
            costing: string;
            /** Waypoints */
            waypoints: [
                number,
                number
            ][];
        };
        /** RouteResponse */
        RouteResponse: {
            /** Coords */
            coords: number[][];
            /** Is Closed Loop */
            is_closed_loop: boolean;
            /** Length M */
            length_m: number;
        };
        /**
         * StartRequest
         * @description Exactly one of `preset`, `waypoints`, or `path` — the API rejects any
         *     other combination. `waypoints` is routed through Valhalla; `path` is a
         *     literal route walked exactly as given, no routing call.
         */
        StartRequest: {
            /** Costing */
            costing?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Loop */
            loop?: boolean | null;
            /** Pace */
            pace?: string | null;
            /** Path */
            path?: [
                number,
                number
            ][] | null;
            /** Preset */
            preset?: string | null;
            /**
             * Scatter M
             * @default 3
             */
            scatter_m: number;
            /** Speed */
            speed?: number | null;
            /** Waypoints */
            waypoints?: [
                number,
                number
            ][] | null;
        };
        /** StatsOut */
        StatsOut: {
            /** Distance M */
            distance_m: number;
            /** Elapsed S */
            elapsed_s: number;
            /** Laps */
            laps: number;
            /** Reconnects */
            reconnects: number;
            /** Ticks */
            ticks: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WalkState
         * @enum {string}
         */
        WalkState: "idle" | "starting" | "walking" | "reconnecting" | "finished" | "error" | "pinned";
        /** WalkStatus */
        WalkStatus: {
            /** Error */
            error?: string | null;
            fix?: components["schemas"]["FixOut"] | null;
            /** Length M */
            length_m?: number | null;
            /**
             * Loop
             * @default false
             */
            loop: boolean;
            /** Pace */
            pace?: string | null;
            /** Preset Name */
            preset_name?: string | null;
            /** Route */
            route?: number[][];
            state: components["schemas"]["WalkState"];
            stats?: components["schemas"]["StatsOut"] | null;
            /** Trail */
            trail?: components["schemas"]["FixOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    device_status_api_device_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceStatus"];
                };
            };
        };
    };
    set_pin_api_pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_places_api_places_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacesListOut"];
                };
            };
        };
    };
    create_place_api_places_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_place_api_places__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetsListOut"];
                };
            };
        };
    };
    create_preset_api_presets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_preset_api_presets__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_route_api_route_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    walk_status_api_walk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkStatus"];
                };
            };
        };
    };
    start_walk_api_walk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_walk_api_walk_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkStatus"];
                };
            };
        };
    };
    reroute_walk_api_walk_route_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
