/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Pin */
        post: operations["set_pin_api_pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_presets_get"];
        put?: never;
        /** Create Preset */
        post: operations["create_preset_api_presets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Route */
        post: operations["build_route_api_route_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/walk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Walk Status */
        get: operations["walk_status_api_walk_get"];
        put?: never;
        /** Start Walk */
        post: operations["start_walk_api_walk_post"];
        /** Stop Walk */
        delete: operations["stop_walk_api_walk_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FixOut */
        FixOut: {
            /** Distance M */
            distance_m: number;
            /** Elapsed S */
            elapsed_s: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Paused */
            paused: boolean;
            /** Speed Mps */
            speed_mps: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PinRequest
         * @description A single point to hold the device at — the GUI's `ios-loc set`.
         */
        PinRequest: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** PresetIn */
        PresetIn: {
            /**
             * Loop
             * @default false
             */
            loop: boolean;
            /** Name */
            name: string;
            /**
             * Profile
             * @default walk
             */
            profile: string;
            /** Waypoints */
            waypoints: [
                number,
                number
            ][];
        };
        /** PresetOut */
        PresetOut: {
            /** Loop */
            loop: boolean;
            /** Name */
            name: string;
            /** Profile */
            profile: string;
            /** Waypoints */
            waypoints: number[][];
        };
        /** PresetsListOut */
        PresetsListOut: {
            /** Offline */
            offline: boolean;
            /** Presets */
            presets: components["schemas"]["PresetOut"][];
            /** Profiles */
            profiles: string[];
        };
        /** RouteRequest */
        RouteRequest: {
            /**
             * Costing
             * @default pedestrian
             */
            costing: string;
            /** Waypoints */
            waypoints: [
                number,
                number
            ][];
        };
        /** RouteResponse */
        RouteResponse: {
            /** Coords */
            coords: number[][];
            /** Is Closed Loop */
            is_closed_loop: boolean;
            /** Length M */
            length_m: number;
        };
        /**
         * StartRequest
         * @description Either `preset` or `waypoints` — the API rejects both and neither.
         */
        StartRequest: {
            /** Costing */
            costing?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Loop */
            loop?: boolean | null;
            /** Preset */
            preset?: string | null;
            /** Profile */
            profile?: string | null;
            /**
             * Scatter M
             * @default 3
             */
            scatter_m: number;
            /** Speed */
            speed?: number | null;
            /** Waypoints */
            waypoints?: [
                number,
                number
            ][] | null;
        };
        /** StatsOut */
        StatsOut: {
            /** Distance M */
            distance_m: number;
            /** Elapsed S */
            elapsed_s: number;
            /** Laps */
            laps: number;
            /** Reconnects */
            reconnects: number;
            /** Ticks */
            ticks: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WalkState
         * @enum {string}
         */
        WalkState: "idle" | "starting" | "walking" | "reconnecting" | "finished" | "error" | "pinned";
        /** WalkStatus */
        WalkStatus: {
            /** Error */
            error?: string | null;
            fix?: components["schemas"]["FixOut"] | null;
            /** Length M */
            length_m?: number | null;
            /**
             * Loop
             * @default false
             */
            loop: boolean;
            /** Preset Name */
            preset_name?: string | null;
            /** Profile */
            profile?: string | null;
            /** Route */
            route?: number[][];
            state: components["schemas"]["WalkState"];
            stats?: components["schemas"]["StatsOut"] | null;
            /** Trail */
            trail?: components["schemas"]["FixOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    set_pin_api_pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetsListOut"];
                };
            };
        };
    };
    create_preset_api_presets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_route_api_route_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    walk_status_api_walk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkStatus"];
                };
            };
        };
    };
    start_walk_api_walk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_walk_api_walk_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkStatus"];
                };
            };
        };
    };
}
